# https://alacritty.org/config-alacritty.html
[window]
opacity = 0.8
decorations = "None"

[font]
size = 14.0
normal = { family = "HackGen Console NF", style="Regular" }
bold = { family = "HackGen Console NF", style="Bold" }
